# Install and launch Ren'Py games on Linux/macOS (lib/ first, sdk/ fallback)

_unren_detect_game_basename() {
    local app="$1" f base

    for f in "$app"/*.exe; do
        [[ -f "$f" ]] || continue
        base="$(basename "$f" .exe)"
        case "$base" in
            renpy|renpy.exe|python|pythonw) continue ;;
        esac
        printf '%s\n' "$base"
        return 0
    done

    for f in "$app"/*.sh; do
        [[ -f "$f" ]] || continue
        base="$(basename "$f" .sh)"
        case "$base" in
            UnRen|renpy|renpy3|renpy2) continue ;;
        esac
        printf '%s\n' "$base"
        return 0
    done

    for f in "$app"/*.py; do
        [[ -f "$f" ]] || continue
        base="$(basename "$f" .py)"
        case "$base" in
            renpy|renpy3|renpy2) continue ;;
        esac
        printf '%s\n' "$base"
        return 0
    done

    if [[ -f "${UNREN_GAME}/options.rpy" ]]; then
        base="$(grep -m1 'define build\.name' "${UNREN_GAME}/options.rpy" 2>/dev/null \
            | sed -n 's/.*"\([^"]*\)".*/\1/p')"
        if [[ -n "$base" ]]; then
            printf '%s\n' "$base"
            return 0
        fi
    fi

    printf '%s\n' "$(basename "$app")"
}

_unren_launch_lib_dir() {
    local app="$1" py_major="$2" platform="$3"
    local game_lib sdk_root sdk_lib

    game_lib="${app}/lib/py${py_major}-${platform}"
    if [[ -d "$game_lib" ]]; then
        chmod -f +x "${game_lib}/python" "${game_lib}/renpy" "${game_lib}/"* 2>/dev/null || true
    fi
    if [[ -d "$game_lib" ]] && {
        [[ -x "${game_lib}/renpy" || -x "${game_lib}/python" ]]
    }; then
        printf '%s\n' "$game_lib"
        return 0
    fi

    if _unren_resolve_sdk_runtime "$app" "$py_major" "$platform" sdk_root sdk_lib; then
        printf '%s\n' "$sdk_lib"
        return 0
    fi

    return 1
}

_unren_launcher_sdk_elif_block() {
    local app="$1" py_major="$2" platform="$3"
    local slice sdk_root lib_dir rel_lib phome py_args layout ld_line

    while IFS= read -r slice; do
        [[ -n "$slice" ]] || continue
        sdk_root="$(_unren_sdk_slice_dir "$slice")"
        lib_dir="$(_unren_sdk_lib_dir "$sdk_root" "$py_major" "$platform")" || continue
        _unren_sdk_lib_usable "$lib_dir" || continue

        rel_lib="${lib_dir#"${app}/"}"
        phome="$(_unren_sdk_pythonhome "$sdk_root" "$lib_dir")"
        py_args="$(_unren_sdk_py_args "$sdk_root")"
        layout="$(_unren_sdk_layout "$sdk_root")"
        rel_sdk="${sdk_root#"${app}/"}"
        case "$layout" in
            renpy6|renpy5)
                ld_line='    SDK_LD_PATH="$LIB:$LIB/lib"'
                renpy_py_line="    SDK_RENPY_PY=\"\$ROOT/${rel_sdk}/renpy.py\""
                ;;
            *)
                ld_line='    SDK_LD_PATH="$LIB"'
                renpy_py_line='    SDK_RENPY_PY=""'
                ;;
        esac

        printf '%s\n' \
            "elif [ -d \"\$ROOT/${rel_lib}\" ] && { [ -x \"\$ROOT/${rel_lib}/renpy\" ] || [ -x \"\$ROOT/${rel_lib}/python\" ] || [ -x \"\$ROOT/${rel_lib}/python.real\" ]; }; then" \
            "    LIB=\"\$ROOT/${rel_lib}\"" \
            "    SDK_PYHOME=\"\$ROOT/${phome#"${app}/"}\"" \
            "    SDK_PY_ARGS=\"${py_args}\"" \
            "$ld_line" \
            "$renpy_py_line"
    done < <(_unren_sdk_fallback_chain "$app")
}

unren_install_launcher() {
    local basename="${1-}" sh_path py_path sdk_elifs
    local platform py_major lib_dir sdk_root

    if [[ -z "$basename" ]]; then
        basename="$(_unren_detect_game_basename "$UNREN_APP")"
    fi
    sh_path="${UNREN_APP}/${basename}.sh"
    py_path="${UNREN_APP}/${basename}.py"

    platform="$(_unren_renpy_platform)"
    py_major="$(_unren_guess_python_major "$UNREN_APP" "$platform")"
    sdk_elifs="$(_unren_launcher_sdk_elif_block "$UNREN_APP" "$py_major" "$platform")"

    if ! lib_dir="$(_unren_launch_lib_dir "$UNREN_APP" "$py_major" "$platform")"; then
        echo "  No Ren'Py runtime for ${platform} in lib/ or sdk/."
        echo "  Copy UnRen-Desktop with sdk/, or use a Linux/macOS game build."
        return 0
    fi

    cat >"$sh_path" <<LAUNCHER
#!/bin/sh
# Generated by UnRen-Desktop — uses game lib/ when present, otherwise sdk/

SCRIPT="\$0"
while [ -L "\$SCRIPT" ]; do
    LINK=\$(readlink "\$SCRIPT")
    case "\$LINK" in
        /*) SCRIPT="\$LINK" ;;
        *) SCRIPT="\$(dirname "\$SCRIPT")/\$LINK" ;;
    esac
done

ROOT=\$(cd "\$(dirname "\$SCRIPT")" && pwd)
BASEFILE=\$(basename "\$SCRIPT" .sh)
SDK_PYHOME=""
SDK_LD_PATH=""
SDK_PY_ARGS=""
SDK_RENPY_PY=""

if [ -z "\$RENPY_PLATFORM" ]; then
    RENPY_PLATFORM="\$(uname -s)-\$(uname -m)"
    case "\$RENPY_PLATFORM" in
        Darwin-*|mac-*) RENPY_PLATFORM="mac-universal" ;;
        *-x86_64|amd64) RENPY_PLATFORM="linux-x86_64" ;;
        *-i*86) RENPY_PLATFORM="linux-i686" ;;
        Linux-*) RENPY_PLATFORM="linux-\$(uname -m)" ;;
    esac
fi

PYTHON="py${py_major}"
GAME_LIB="\$ROOT/lib/\$PYTHON-\$RENPY_PLATFORM"

if [ -d "\$GAME_LIB" ] && { [ -x "\$GAME_LIB/renpy" ] || [ -x "\$GAME_LIB/python" ]; }; then
    LIB="\$GAME_LIB"
${sdk_elifs}
else
    echo "Ren'Py platform files not found for \$RENPY_PLATFORM in:"
    echo "  \$ROOT/lib/"
    echo "  \$ROOT/sdk/"
    exit 1
fi

cd "\$ROOT" || exit 1

if [ -d "\$ROOT/lib/python3.12" ]; then
    export PYTHONHOME="\$ROOT/lib/python3.12"
elif [ -d "\$ROOT/lib/python3.9" ]; then
    export PYTHONHOME="\$ROOT/lib/python3.9"
elif [ -d "\$ROOT/lib/python2.7" ]; then
    export PYTHONHOME="\$ROOT/lib/python2.7"
elif [ -d "\$ROOT/lib/pythonlib2.7" ]; then
    export PYTHONHOME="\$ROOT/lib/pythonlib2.7"
elif [ -n "\$SDK_PYHOME" ] && [ -d "\$SDK_PYHOME" ]; then
    export PYTHONHOME="\$SDK_PYHOME"
fi
unset PYTHONPATH

if [ -n "\$SDK_LD_PATH" ]; then
    export LD_LIBRARY_PATH="\$SDK_LD_PATH\${LD_LIBRARY_PATH:+:\$LD_LIBRARY_PATH}"
fi

if [ -e "\$LIB/\$BASEFILE" ]; then
    exec \${RENPY_GDB} "\$LIB/\$BASEFILE" "\$ROOT" run "\$@"
fi

# Ren'Py 5/6 SDK slices: use bundled sdk/renpy.py engine (pygame_sdl2, matching common/).
if [ -n "\$SDK_RENPY_PY" ] && [ -f "\$SDK_RENPY_PY" ] && { [ -x "\$LIB/python" ] || [ -x "\$LIB/python.real" ]; }; then
    PYBIN="python"
    [ -x "\$LIB/python.real" ] && PYBIN="python.real"
    exec \${RENPY_GDB} "\$LIB/\$PYBIN" \$SDK_PY_ARGS "\$SDK_RENPY_PY" "\$ROOT" run "\$@"
fi

# Modern SDK / native lib: game .py uses the game's bundled renpy/ tree.
if [ -f "\$ROOT/\${BASEFILE}.py" ] && { [ -x "\$LIB/python" ] || [ -x "\$LIB/python.real" ]; }; then
    PYBIN="python"
    [ -x "\$LIB/python.real" ] && PYBIN="python.real"
    exec \${RENPY_GDB} "\$LIB/\$PYBIN" \$SDK_PY_ARGS "\$ROOT/\${BASEFILE}.py" "\$ROOT" run "\$@"
fi

if [ -z "\$SDK_RENPY_PY" ] && [ -e "\$LIB/renpy" ]; then
    exec \${RENPY_GDB} "\$LIB/renpy" "\$ROOT" run "\$@"
fi

if { [ -x "\$LIB/python" ] || [ -x "\$LIB/python.real" ]; } && [ -f "\$ROOT/renpy.py" ]; then
    PYBIN="python"
    [ -x "\$LIB/python.real" ] && PYBIN="python.real"
    exec \${RENPY_GDB} "\$LIB/\$PYBIN" \$SDK_PY_ARGS "\$ROOT/renpy.py" "\$ROOT" run "\$@"
fi

echo "Could not launch game from \$LIB"
exit 1
LAUNCHER

    chmod +x "$sh_path"

    if [[ ! -f "$py_path" ]]; then
        if [[ -f "${UNREN_APP}/renpy.py" ]]; then
            cp -a "${UNREN_APP}/renpy.py" "$py_path"
        elif _unren_resolve_sdk_runtime "$UNREN_APP" "$py_major" "$platform" sdk_root lib_dir &&
             [[ -f "${sdk_root}/renpy.py" ]]; then
            cp -a "${sdk_root}/renpy.py" "$py_path"
        else
            echo "  Warning: could not create ${basename}.py (renpy.py template missing)"
        fi
    fi

    if [[ -f "$py_path" ]]; then
        chmod +x "$py_path" 2>/dev/null || true
    fi

    if [[ "$lib_dir" == "${UNREN_APP}/lib/"* ]]; then
        echo "  Launcher: ${basename}.sh (runtime: game lib/)"
    else
        local sdk_slice="${lib_dir#"${UNREN_APP}/sdk/"}"
        sdk_slice="${sdk_slice%%/*}"
        echo "  Launcher: ${basename}.sh (runtime: sdk/${sdk_slice})"
    fi
    [[ -f "$py_path" ]] && echo "  Bootstrap: ${basename}.py"

    printf '%s\n' "$sh_path"
}

unren_launch_game() {
    local basename sh_path

    basename="$(_unren_detect_game_basename "$UNREN_APP")"
    sh_path="${UNREN_APP}/${basename}.sh"

    if [[ ! -x "$sh_path" ]]; then
        echo "  Installing game launcher for ${basename} ..."
        echo
        sh_path="$(unren_install_launcher "$basename")" || return 1
        echo
    fi

    echo "  Launching ${basename} ..."
    echo
    set +e
    exec "${sh_path}"
    local rc=$?
    set -e
    if (( rc != 0 )); then
        echo
        echo "  Launch failed (exit ${rc})."
    fi
    return 0
}
