# Install and launch Ren'Py games on Linux/macOS (lib/ first, sdk/ fallback)

_unren_detect_game_basename() {
    local app="$1" f base

    for f in "$app"/*.exe; do
        [[ -f "$f" ]] || continue
        base="$(basename "$f" .exe)"
        case "$base" in
            renpy|renpy.exe|python|pythonw) continue ;;
        esac
        printf '%s\n' "$base"
        return 0
    done

    for f in "$app"/*.sh; do
        [[ -f "$f" ]] || continue
        base="$(basename "$f" .sh)"
        case "$base" in
            UnRen|renpy|renpy3|renpy2) continue ;;
        esac
        printf '%s\n' "$base"
        return 0
    done

    for f in "$app"/*.py; do
        [[ -f "$f" ]] || continue
        base="$(basename "$f" .py)"
        case "$base" in
            renpy|renpy3|renpy2) continue ;;
        esac
        printf '%s\n' "$base"
        return 0
    done

    if [[ -f "${UNREN_GAME}/options.rpy" ]]; then
        base="$(grep -m1 'define build\.name' "${UNREN_GAME}/options.rpy" 2>/dev/null \
            | sed -n 's/.*"\([^"]*\)".*/\1/p')"
        if [[ -n "$base" ]]; then
            printf '%s\n' "$base"
            return 0
        fi
    fi

    printf '%s\n' "$(basename "$app")"
}

_unren_launch_lib_dir() {
    local app="$1" py_major="$2" platform="$3"
    local game_lib sdk_root sdk_lib

    game_lib="${app}/lib/py${py_major}-${platform}"
    if [[ -d "$game_lib" ]]; then
        chmod -f +x "${game_lib}/python" "${game_lib}/renpy" "${game_lib}/"* 2>/dev/null || true
    fi
    if [[ -d "$game_lib" ]] && {
        [[ -x "${game_lib}/renpy" || -x "${game_lib}/python" ]]
    }; then
        printf '%s\n' "$game_lib"
        return 0
    fi

    if [[ "$py_major" == 3 ]]; then
        sdk_root="${SDK_PY3_DIR}"
    else
        sdk_root="${SDK_PY2_DIR}"
    fi

    sdk_lib="${sdk_root}/lib/py${py_major}-${platform}"
    if [[ -d "$sdk_lib" ]] && {
        [[ -x "${sdk_lib}/renpy" || -x "${sdk_lib}/python" ]]
    }; then
        printf '%s\n' "$sdk_lib"
        return 0
    fi

    return 1
}

unren_install_launcher() {
    local basename="${1-}" sh_path py_path
    local platform py_major lib_dir

    if [[ -z "$basename" ]]; then
        basename="$(_unren_detect_game_basename "$UNREN_APP")"
    fi
    sh_path="${UNREN_APP}/${basename}.sh"
    py_path="${UNREN_APP}/${basename}.py"

    platform="$(_unren_renpy_platform)"
    py_major="$(_unren_guess_python_major "$UNREN_APP" "$platform")"

    if ! lib_dir="$(_unren_launch_lib_dir "$UNREN_APP" "$py_major" "$platform")"; then
        echo "  No Ren'Py runtime for ${platform} in lib/ or sdk/."
        echo "  Copy UnRen-Desktop with sdk/, or use a Linux/macOS game build."
        return 0
    fi

    cat >"$sh_path" <<'LAUNCHER'
#!/bin/sh
# Generated by UnRen-Desktop — uses game lib/ when present, otherwise sdk/

SCRIPT="$0"
while [ -L "$SCRIPT" ]; do
    LINK=$(readlink "$SCRIPT")
    case "$LINK" in
        /*) SCRIPT="$LINK" ;;
        *) SCRIPT="$(dirname "$SCRIPT")/$LINK" ;;
    esac
done

ROOT=$(cd "$(dirname "$SCRIPT")" && pwd)
BASEFILE=$(basename "$SCRIPT" .sh)

if [ -z "$RENPY_PLATFORM" ]; then
    RENPY_PLATFORM="$(uname -s)-$(uname -m)"
    case "$RENPY_PLATFORM" in
        Darwin-*|mac-*) RENPY_PLATFORM="mac-universal" ;;
        *-x86_64|amd64) RENPY_PLATFORM="linux-x86_64" ;;
        *-i*86) RENPY_PLATFORM="linux-i686" ;;
        Linux-*) RENPY_PLATFORM="linux-$(uname -m)" ;;
    esac
fi

PYTHON="__PY_MAJOR__"
GAME_LIB="$ROOT/lib/$PYTHON-$RENPY_PLATFORM"

if [ -d "$GAME_LIB" ] && { [ -x "$GAME_LIB/renpy" ] || [ -x "$GAME_LIB/python" ]; }; then
    LIB="$GAME_LIB"
elif [ "__PY_MAJOR__" = "py2" ] && [ -d "$ROOT/sdk/py2-7.8.7/lib/py2-$RENPY_PLATFORM" ] && \
     { [ -x "$ROOT/sdk/py2-7.8.7/lib/py2-$RENPY_PLATFORM/renpy" ] || \
       [ -x "$ROOT/sdk/py2-7.8.7/lib/py2-$RENPY_PLATFORM/python" ]; }; then
    LIB="$ROOT/sdk/py2-7.8.7/lib/py2-$RENPY_PLATFORM"
elif [ -d "$ROOT/sdk/py3-8.5.3/lib/py3-$RENPY_PLATFORM" ] && \
     { [ -x "$ROOT/sdk/py3-8.5.3/lib/py3-$RENPY_PLATFORM/renpy" ] || \
       [ -x "$ROOT/sdk/py3-8.5.3/lib/py3-$RENPY_PLATFORM/python" ]; }; then
    LIB="$ROOT/sdk/py3-8.5.3/lib/py3-$RENPY_PLATFORM"
elif [ -d "$ROOT/sdk/py2-7.8.7/lib/py2-$RENPY_PLATFORM" ] && \
     { [ -x "$ROOT/sdk/py2-7.8.7/lib/py2-$RENPY_PLATFORM/renpy" ] || \
       [ -x "$ROOT/sdk/py2-7.8.7/lib/py2-$RENPY_PLATFORM/python" ]; }; then
    LIB="$ROOT/sdk/py2-7.8.7/lib/py2-$RENPY_PLATFORM"
else
    echo "Ren'Py platform files not found for $RENPY_PLATFORM in:"
    echo "  $ROOT/lib/"
    echo "  $ROOT/sdk/"
    exit 1
fi

cd "$ROOT" || exit 1

# Prefer native stubs; set PYTHONHOME when falling back to sdk python + .py bootstrap.
if [ -d "$ROOT/lib/python3.12" ]; then
    export PYTHONHOME="$ROOT/lib/python3.12"
elif [ -d "$ROOT/lib/python3.9" ]; then
    export PYTHONHOME="$ROOT/lib/python3.9"
elif [ -d "$ROOT/lib/python2.7" ]; then
    export PYTHONHOME="$ROOT/lib/python2.7"
elif [ -d "$ROOT/lib/pythonlib2.7" ]; then
    export PYTHONHOME="$ROOT/lib/pythonlib2.7"
elif [ -d "$ROOT/sdk/py3-8.5.3/lib/python3.12" ]; then
    export PYTHONHOME="$ROOT/sdk/py3-8.5.3/lib/python3.12"
elif [ -d "$ROOT/sdk/py2-7.8.7/lib/python2.7" ]; then
    export PYTHONHOME="$ROOT/sdk/py2-7.8.7/lib/python2.7"
fi
unset PYTHONPATH

if [ -e "$LIB/$BASEFILE" ]; then
    exec ${RENPY_GDB} "$LIB/$BASEFILE" "$ROOT" run "$@"
fi

if [ -e "$LIB/renpy" ]; then
    exec ${RENPY_GDB} "$LIB/renpy" "$ROOT" run "$@"
fi

if [ -f "$ROOT/${BASEFILE}.py" ] && [ -x "$LIB/python" ]; then
    exec ${RENPY_GDB} "$LIB/python" "$ROOT/${BASEFILE}.py" "$ROOT" run "$@"
fi

if [ -x "$LIB/python" ] && [ -f "$ROOT/renpy.py" ]; then
    exec ${RENPY_GDB} "$LIB/python" "$ROOT/renpy.py" "$ROOT" run "$@"
fi

echo "Could not launch game from $LIB"
exit 1
LAUNCHER

    sed "s/__PY_MAJOR__/py${py_major}/g" "$sh_path" >"${sh_path}.tmp" && mv -f "${sh_path}.tmp" "$sh_path"
    chmod +x "$sh_path"

    if [[ ! -f "$py_path" ]]; then
        if [[ -f "${UNREN_APP}/renpy.py" ]]; then
            cp -a "${UNREN_APP}/renpy.py" "$py_path"
        elif [[ "$py_major" == 3 && -f "${SDK_PY3_DIR}/renpy.py" ]]; then
            cp -a "${SDK_PY3_DIR}/renpy.py" "$py_path"
        elif [[ -f "${SDK_PY2_DIR}/renpy.py" ]]; then
            cp -a "${SDK_PY2_DIR}/renpy.py" "$py_path"
        else
            echo "  Warning: could not create ${basename}.py (renpy.py template missing)"
        fi
    fi

    if [[ -f "$py_path" ]]; then
        chmod +x "$py_path" 2>/dev/null || true
    fi

    if [[ "$lib_dir" == "${UNREN_APP}/lib/"* ]]; then
        echo "  Launcher: ${basename}.sh (runtime: game lib/)"
    else
        echo "  Launcher: ${basename}.sh (runtime: sdk/ — no ${platform} lib/ in game)"
    fi
    [[ -f "$py_path" ]] && echo "  Bootstrap: ${basename}.py"

    printf '%s\n' "$sh_path"
}

unren_launch_game() {
    local basename sh_path

    basename="$(_unren_detect_game_basename "$UNREN_APP")"
    sh_path="${UNREN_APP}/${basename}.sh"

    if [[ ! -x "$sh_path" ]]; then
        echo "  Installing game launcher for ${basename} ..."
        echo
        sh_path="$(unren_install_launcher "$basename")" || return 1
        echo
    fi

    echo "  Launching ${basename} ..."
    echo
    set +e
    exec "${sh_path}"
    local rc=$?
    set -e
    if (( rc != 0 )); then
        echo
        echo "  Launch failed (exit ${rc})."
    fi
    return 0
}
