#!/bin/sh
# Generated by UnRen-Desktop from unren/templates/renpy-desktop.sh
# Re-run UnRen option g, 8, or 9 to regenerate after updates.
#
# Display (Linux): py2 / SDK-fallback runtimes lack native Wayland in bundled
# pygame_sdl2. On a Wayland session we set SDL_VIDEODRIVER=x11 (XWayland).
# py3 runtimes: leave SDL unset — modern SDL2 picks Wayland or X11 automatically.
# Override: SDL_VIDEODRIVER=wayland|x11  or  UNREN_SDL_VIDEODRIVER=...

SCRIPT="$0"
while [ -L "$SCRIPT" ]; do
    LINK=$(readlink "$SCRIPT")
    case "$LINK" in
        /*) SCRIPT="$LINK" ;;
        *) SCRIPT="$(dirname "$SCRIPT")/$LINK" ;;
    esac
done

ROOT=$(cd "$(dirname "$SCRIPT")" && pwd)
BASEFILE=$(basename "$SCRIPT" .sh)
SDK_PYHOME=""
SDK_LD_PATH=""
SDK_PY_ARGS=""
SDK_RENPY_PY=""

if [ -z "$RENPY_PLATFORM" ]; then
    RENPY_PLATFORM="$(uname -s)-$(uname -m)"
    case "$RENPY_PLATFORM" in
        Darwin-*|mac-*) RENPY_PLATFORM="mac-universal" ;;
        *-x86_64|amd64) RENPY_PLATFORM="linux-x86_64" ;;
        *-i*86) RENPY_PLATFORM="linux-i686" ;;
        Linux-*) RENPY_PLATFORM="linux-$(uname -m)" ;;
    esac
fi

PYTHON="py@@UNREN_PY_MAJOR@@"
GAME_LIB="$ROOT/lib/$PYTHON-$RENPY_PLATFORM"

if [ -d "$GAME_LIB" ] && { [ -x "$GAME_LIB/renpy" ] || [ -x "$GAME_LIB/python" ]; }; then
    LIB="$GAME_LIB"
@@UNREN_SDK_ELIFS@@
else
    echo "Ren'Py platform files not found for $RENPY_PLATFORM in:"
    echo "  $ROOT/lib/"
    echo "  $ROOT/sdk/"
    exit 1
fi

cd "$ROOT" || exit 1

@@UNREN_SDL_BLOCK@@
if [ -d "$ROOT/lib/python3.12" ]; then
    export PYTHONHOME="$ROOT/lib/python3.12"
elif [ -d "$ROOT/lib/python3.9" ]; then
    export PYTHONHOME="$ROOT/lib/python3.9"
elif [ -d "$ROOT/lib/python2.7" ]; then
    export PYTHONHOME="$ROOT/lib/python2.7"
elif [ -d "$ROOT/lib/pythonlib2.7" ]; then
    export PYTHONHOME="$ROOT/lib/pythonlib2.7"
elif [ -n "$SDK_PYHOME" ] && [ -d "$SDK_PYHOME" ]; then
    export PYTHONHOME="$SDK_PYHOME"
fi
unset PYTHONPATH

if [ -n "$SDK_LD_PATH" ]; then
    export LD_LIBRARY_PATH="$SDK_LD_PATH${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
fi

if [ -e "$LIB/$BASEFILE" ]; then
    exec ${RENPY_GDB} "$LIB/$BASEFILE" "$ROOT" run "$@"
fi

# Ren'Py 5/6 SDK slices: use bundled sdk/renpy.py engine (pygame_sdl2, matching common/).
if [ -n "$SDK_RENPY_PY" ] && [ -f "$SDK_RENPY_PY" ] && { [ -x "$LIB/python" ] || [ -x "$LIB/python.real" ]; }; then
    PYBIN="python"
    [ -x "$LIB/python.real" ] && PYBIN="python.real"
    exec ${RENPY_GDB} "$LIB/$PYBIN" $SDK_PY_ARGS "$SDK_RENPY_PY" "$ROOT" run "$@"
fi

# Modern SDK / native lib: game .py uses the game's bundled renpy/ tree.
if [ -f "$ROOT/${BASEFILE}.py" ] && { [ -x "$LIB/python" ] || [ -x "$LIB/python.real" ]; }; then
    PYBIN="python"
    [ -x "$LIB/python.real" ] && PYBIN="python.real"
    exec ${RENPY_GDB} "$LIB/$PYBIN" $SDK_PY_ARGS "$ROOT/${BASEFILE}.py" "$ROOT" run "$@"
fi

if [ -z "$SDK_RENPY_PY" ] && [ -e "$LIB/renpy" ]; then
    exec ${RENPY_GDB} "$LIB/renpy" "$ROOT" run "$@"
fi

if { [ -x "$LIB/python" ] || [ -x "$LIB/python.real" ]; } && [ -f "$ROOT/renpy.py" ]; then
    PYBIN="python"
    [ -x "$LIB/python.real" ] && PYBIN="python.real"
    exec ${RENPY_GDB} "$LIB/$PYBIN" $SDK_PY_ARGS "$ROOT/renpy.py" "$ROOT" run "$@"
fi

echo "Could not launch game from $LIB"
exit 1
