#!/bin/sh
# Generated by UnRen-Desktop from unren/templates/renpy-desktop.sh
# Re-run UnRen option g, 8, or 9 to regenerate after updates.
#
# Display (Linux): py2 runtimes force SDL_VIDEODRIVER=x11 (XWayland). Needed when
# the desktop sets SDL_VIDEODRIVER=wayland (common on KDE) or on Wayland sessions.
# py3 runtimes: leave SDL unset unless you override (see README).
# Override: UNREN_SDL_VIDEODRIVER=wayland|x11

SCRIPT="$0"
while [ -L "$SCRIPT" ]; do
    LINK=$(readlink "$SCRIPT")
    case "$LINK" in
        /*) SCRIPT="$LINK" ;;
        *) SCRIPT="$(dirname "$SCRIPT")/$LINK" ;;
    esac
done

ROOT=$(cd "$(dirname "$SCRIPT")" && pwd)
BASEFILE=$(basename "$SCRIPT" .sh)
SDK_PYHOME=""
SDK_LD_PATH=""
SDK_PY_ARGS=""
SDK_RENPY_PY=""

if [ -z "$RENPY_PLATFORM" ]; then
    RENPY_PLATFORM="$(uname -s)-$(uname -m)"
    case "$RENPY_PLATFORM" in
        Darwin-*|mac-*) RENPY_PLATFORM="mac-universal" ;;
        *-x86_64|amd64) RENPY_PLATFORM="linux-x86_64" ;;
        *-i*86) RENPY_PLATFORM="linux-i686" ;;
        Linux-*) RENPY_PLATFORM="linux-$(uname -m)" ;;
    esac
fi

PYTHON="py@@UNREN_PY_MAJOR@@"
@@UNREN_GAME_LIB_IF@@
@@UNREN_SDK_ELIFS@@
else
    echo "Ren'Py platform files not found for $RENPY_PLATFORM in:"
    echo "  $ROOT/lib/"
    echo "  $ROOT/sdk/"
    exit 1
fi

cd "$ROOT" || exit 1

@@UNREN_SDL_BLOCK@@
GAME_PYHOME=""
GAME_PY_ARGS=""
GAME_LD_PATH=""
if [ -f "$LIB/lib/python2.7/site.py" ]; then
    GAME_PYHOME="$LIB/lib/python2.7"
    GAME_PY_ARGS="-EO"
    GAME_LD_PATH="$LIB:$LIB/lib"
elif [ -f "$ROOT/lib/python2.7/site.py" ]; then
    GAME_PYHOME="$ROOT/lib/python2.7"
    GAME_PY_ARGS="-EO"
    GAME_LD_PATH="$LIB"
elif [ -f "$LIB/lib/python2.3/site.py" ]; then
    GAME_PYHOME="$LIB/lib/python2.3"
    GAME_PY_ARGS="-EO"
    GAME_LD_PATH="$LIB:$LIB/lib"
elif [ -f "$LIB/lib/python3.12/site.py" ] || [ -f "$LIB/lib/python3.12/site.pyc" ] || [ -d "$LIB/lib/python3.12/encodings" ]; then
    GAME_PYHOME="$LIB/lib/python3.12"
    GAME_LD_PATH="$LIB"
elif [ -f "$ROOT/lib/python3.12/site.py" ] || [ -f "$ROOT/lib/python3.12/site.pyc" ] || [ -d "$ROOT/lib/python3.12/encodings" ]; then
    GAME_PYHOME="$ROOT/lib/python3.12"
    GAME_LD_PATH="$LIB"
elif [ -f "$LIB/lib/python3.9/site.py" ]; then
    GAME_PYHOME="$LIB/lib/python3.9"
    GAME_LD_PATH="$LIB"
elif [ -f "$ROOT/lib/python3.9/site.py" ]; then
    GAME_PYHOME="$ROOT/lib/python3.9"
    GAME_LD_PATH="$LIB"
elif [ -f "$ROOT/lib/pythonlib2.7/site.py" ]; then
    GAME_PYHOME="$ROOT/lib/pythonlib2.7"
    GAME_PY_ARGS="-EO"
    GAME_LD_PATH="$LIB"
fi

if [ -n "$SDK_PYHOME" ] && [ -d "$SDK_PYHOME" ]; then
    if [ -f "$SDK_PYHOME/site.py" ] || [ -f "$SDK_PYHOME/site.pyc" ] || [ -d "$SDK_PYHOME/encodings" ]; then
        export PYTHONHOME="$SDK_PYHOME"
    fi
elif [ -n "$GAME_PYHOME" ] && [ -d "$GAME_PYHOME" ]; then
    if [ -f "$GAME_PYHOME/site.py" ] || [ -f "$GAME_PYHOME/site.pyc" ] || [ -d "$GAME_PYHOME/encodings" ]; then
        export PYTHONHOME="$GAME_PYHOME"
    fi
fi
unset PYTHONPATH

PYARGS=""
if [ -n "$SDK_PY_ARGS" ]; then
    PYARGS="$SDK_PY_ARGS"
elif [ -n "$GAME_PY_ARGS" ]; then
    PYARGS="$GAME_PY_ARGS"
fi

if [ -n "$SDK_LD_PATH" ]; then
    export LD_LIBRARY_PATH="$SDK_LD_PATH${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
elif [ -n "$GAME_LD_PATH" ]; then
    export LD_LIBRARY_PATH="$GAME_LD_PATH${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
fi

# SDK python + game native renpy/*.so (Windows PC builds): add game lib/ to loader path.
case "$LIB" in
    */sdk/*)
        UNREN_SDK_ROOT="${LIB%%/lib/*}"
        export UNREN_SDK_ROOT
        for _glib in \
            "$ROOT/lib/linux-x86_64" \
            "$ROOT/lib/linux-i686" \
            "$ROOT/lib/py2-linux-x86_64" \
            "$ROOT/lib/py2-linux-i686"; do
            if [ -f "$_glib/lib/python2.7/renpy/parsersupport.so" ]; then
                export LD_LIBRARY_PATH="$_glib:$_glib/lib${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
                break
            fi
        done
        ;;
esac

if [ -z "${PYTHONHOME:-}" ]; then
    case "$LIB" in
        */py3-*|*/sdk/py3-*|*/py2-*|*/sdk/py2-*|*/linux-x86_64|*/linux-i686)
            ;;
        *)
            echo "Python stdlib missing for runtime in:"
            echo "  $LIB"
            echo "Re-run UnRen option g after: ./scripts/ensure-sdk-runtime.sh"
            exit 1
            ;;
    esac
fi

if [ -e "$LIB/$BASEFILE" ]; then
    exec ${RENPY_GDB} "$LIB/$BASEFILE" "$ROOT" run "$@"
fi

# Ren'Py 5/6 SDK slices: use bundled sdk/renpy.py engine (pygame_sdl2, matching common/).
if [ -n "$SDK_RENPY_PY" ] && [ -f "$SDK_RENPY_PY" ] && { [ -x "$LIB/python" ] || [ -x "$LIB/python.real" ]; }; then
    PYBIN="python"
    [ -x "$LIB/python.real" ] && PYBIN="python.real"
    exec ${RENPY_GDB} "$LIB/$PYBIN" $PYARGS "$SDK_RENPY_PY" "$ROOT" run "$@"
fi

# Modern SDK / native lib: game .py uses the game's bundled renpy/ tree.
if [ -f "$ROOT/${BASEFILE}.py" ] && { [ -x "$LIB/python" ] || [ -x "$LIB/python.real" ]; }; then
    PYBIN="python"
    [ -x "$LIB/python.real" ] && PYBIN="python.real"
    exec ${RENPY_GDB} "$LIB/$PYBIN" $PYARGS "$ROOT/${BASEFILE}.py" "$ROOT" run "$@"
fi

if [ -z "$SDK_RENPY_PY" ] && [ -e "$LIB/renpy" ]; then
    exec ${RENPY_GDB} "$LIB/renpy" "$ROOT" run "$@"
fi

if { [ -x "$LIB/python" ] || [ -x "$LIB/python.real" ]; } && [ -f "$ROOT/renpy.py" ]; then
    PYBIN="python"
    [ -x "$LIB/python.real" ] && PYBIN="python.real"
    exec ${RENPY_GDB} "$LIB/$PYBIN" $PYARGS "$ROOT/renpy.py" "$ROOT" run "$@"
fi

echo "Could not launch game from $LIB"
exit 1
